# Dependencies
markdown:         kramdown 
highlighter:      rouge

# Permalinks
permalink:        pretty

# Optimize Jekyll
exclude:
  - .idea
  - .editorconfig
  - "licenses/*"
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
    sass_dir: _sass
    style: compressed

# Setup
title:            Rust stuff
tagline:          'Embedded engineering and programming stuff'
description:      'Blog with random notes about embedded and non-embedded things'

paginate:         5
baseurl:          ""

excerpt_separator: <!--more-->
sidebar_home_link:  true

plugins: 
 - jekyll-paginate
 - jekyll-gist
 - jekyll-seo-tag
 - jekyll-feed
 - jekyll-sitemap
 - jemoji

url: "https://rs-stuff.dev"
repo: 'https://github.com/vpetrigo'

email: 'vladimir.petrigo@gmail.com'

linkedin: 'https://linkedin.com/in/vladimirpetrigo'

boosty: 'https://boosty.to/vladimir.petrigo'

twitter:
  username: vpetrigo
  card:     summary
  url:      'https://twitter.com/vpetrigo'

google_analytics: G-DNQ2PBCFHS
yandex_analytics: 
  metrics: 56945608
  webmaster: 80fdd0e9729049b7

defaults:
  - scope:
      path:            licenses/
    values:
      sitemap:         false
