# Dependencies
markdown:         kramdown 
highlighter:      rouge

# Permalinks
permalink:        pretty

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
    sass_dir: _sass
    style: compressed

# Setup
title:            Rust stuff
tagline:          'Embedded engineering and programming stuff'
description:      'Blog with random notes about embedded and non-embedded things'

paginate:         5
baseurl:          ""

plugins: 
 - jekyll-paginate
 - jekyll-gist
 - jekyll-seo-tag
 - jekyll-feed
 - jekyll-sitemap
 - jemoji

repo: 'https://github.com/vpetrigo'

email: 'vladimir.petrigo@gmail.com'

linkedin: 'https://linkedin.com/in/vladimirpetrigo'

boosty: 'https://boosty.to/vladimir.petrigo'

twitter:
  username: vpetrigo
  card:     summary
  url:      'https://twitter.com/vpetrigo'

defaults:
  - scope:
      path:            licenses/
    values:
      sitemap:         false
